# Configuration file
configfile: "config/config.yaml"

# Container image
container: "docker://continuumio/miniconda3"

# Workflow rules
include: "rules/resources.smk"
include: "rules/common.smk"
include: "rules/outputs.smk"
include: "rules/processing.smk"
include: "rules/qc.smk"
include: "rules/diffexp.smk"
include: "rules/visualise.smk"
include: "rules/genelevel.smk"
include: "rules/ge.smk"
include: "rules/shiny.smk"

# Target rule
rule all:
    input:
      get_final_output()
