---
title: "Dynamic report"
output: 
  html_document: 
    bootswatch: minty
    base_font:
        google: "Roboto"
params:
  gene: "NA"
  contrast: "NA"
  data: "NA"
---
---
title: "Dynamic report for `r params$gene`"
---
 
```{r, echo=FALSE, results=FALSE, message=FALSE}

packages <- c("ggplot2", "RColorBrewer", "heatmaply","reshape", "edgeR", "knitr", "tidyverse", "kableExtra")
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

#### Packages loading ####
invisible(lapply(packages, library, character.only = TRUE))

data=params$data
```

```{r, echo=FALSE, message=FALSE}
mat <- cpm(data$x$counts, log=TRUE, prior.count = 1)
colnames(mat) <- paste(data$x$samples$group, data$x$samples$Replicate, sep = " - " )
pos=which(grepl(params$gene, rownames(mat)))
mat = mat[c(pos),]
getPalette = colorRampPalette(brewer.pal(9, "Blues"))
heatmaply(mat, col=getPalette, main="Differential expression" )
```

```{r, echo=FALSE, message=FALSE}
colnames(data$corrected)= paste(data$x$samples$group, data$x$samples$Replicate, sep = " - " )
pos=which(grepl(params$gene, rownames(data$corrected)))
corrected = data$corrected[c(pos),]
getPalette = colorRampPalette(brewer.pal(9, "Blues"))
heatmaply(corrected, col=getPalette, main="Batch corrected differential expression")
```

```{r, echo=FALSE, message=FALSE}
mat <- cpm(data$x$counts, log=TRUE, prior.count = 1)
pos=which(grepl(params$gene, rownames(mat)))
mat = data.frame(mat[c(pos),])
mat$Batch=c("Uncorrected")

pos=which(grepl(params$gene, rownames(data$corrected)))
cor_mat = data.frame(data$corrected[c(pos),])
cor_mat$Batch=c("Corrected")
colnames(cor_mat)=colnames(mat)

rbind(mat,cor_mat) %>%
  kbl(caption="Differential expression logCPM") %>%
  kable_minimal()
```

```{r, echo=FALSE, message=FALSE}
name=names(data)[which(str_detect(names(data), "_lrt"))]
split=str_split(name, "_")
dat=NULL
for (i in as.vector(sapply(split,"[[",1))) {
  obj <- get('data')[[paste0(i, "_camera")]]
  colnames(obj)=c("nGuides", "Direction", "Pvalue", "FDR", "Gene")
  obj$Contrast=paste(i)
  dat=rbind(dat,obj)
}
dat=dat[,c(6,5,1,2,3,4)]
rownames(dat)=c()
dat[dat$Gene==params$gene,] %>% 
  kbl(caption="Camera") %>%
  kable_minimal()
```

```{r, echo=FALSE, message=FALSE}
name=names(data)[which(str_detect(names(data), "_lrt"))]
split=str_split(name, "_")
dat=NULL
for (i in as.vector(sapply(split,"[[",1))) {
  obj <- get('data')[[paste0(i, "_genelevel")]]
  obj$contrast=paste(i)
  dat=rbind(dat,obj)
}
colnames(dat)=c("Gene", "nGuides", 	"Mean logFC", "IQR logFC", "Direction mean logFC",	"Direction smallest Pvalue", "Stouffer's Pvalue",	"Stouffer's FDR", 	"Contrast")
dat=dat[,c(9,1:8)]
rownames(dat)=c()
dat[dat$Gene==params$gene,] %>% 
  kbl(caption="Gene level") %>%
  kable_minimal() 
```

```{r, echo=FALSE, message=FALSE}
name=names(data)[which(str_detect(names(data), "_lrt"))]
split=str_split(name, "_")

for (i in as.vector(sapply(split,"[[",1))) {
  
  obj <- get('data')[[paste0(i, "_lrt")]]
  genesymbollist = list()
  genesymbols=as.character(data$x$genes$Gene)
  unq = unique(genesymbols)
  unq = unq[!is.na(unq)]
    
  for (g in unq) {
    sel = genesymbols == g & !is.na(genesymbols)
    if (sum(sel) > 1) 
      genesymbollist[[g]] =which(sel)
  }
  barcodeplot(obj$table$logFC,index=genesymbollist[[params$gene]], main=paste0("Barcodeplot for ", params$contrast),
              labels=c("Negative logFC", "Positive logFC"),
              quantile=c(-0.5,0.5))
    
}
```

```{r, echo=FALSE, message=FALSE}
name=names(data)[which(str_detect(names(data), "_lrt"))]
split=str_split(name, "_")
compare=NULL
for (i in as.vector(sapply(split,"[[",1))) {
  obj <- get('data')[[paste0(i, "_lrt")]]
  compare=cbind(compare,obj$table$logFC)
}

colnames(compare)=as.vector(sapply(split,"[[",1))
rownames(compare)=rownames(obj)
res=compare[which(str_detect(rownames(compare), params$gene)),]
d=melt(t(res), id.vars=colnames(res))
ggplotly(
  d %>% ggplot(aes(x=X1, y=value, fill=X1)) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter(aes(colour = X2)) +
    theme_bw() +
    xlab("") +
    guides(fill = "none") +
    ggtitle(paste(params$gene)) +
    theme(plot.title = element_text(hjust = 0.5)) +
    scale_colour_discrete(name  ="Hairpin") +
    scale_y_continuous(name ="logFC") +
    scale_x_discrete(name ="Contrast")
  )
```

```{r, echo=FALSE, message=FALSE}
name=names(data)[which(str_detect(names(data), "_lrt"))]
split=str_split(name, "_")
vector=NULL
for (i in as.vector(sapply(split,"[[",1))) {
  obj <- get('data')[[paste0(i, "_lrt")]]
  df=obj$table[which(str_detect(rownames(obj$table),  params$gene)),]
  vector=cbind(vector,mean(df$logFC))
}
vector=data.frame(cbind(params$gene, vector))

colnames(vector)=c("Gene", as.vector(sapply(split,"[[",1)))
vector %>% 
  kbl(caption="Mean logFC across contrasts") %>%
  kable_minimal()
```