# specify organism
organism: org.Mm.eg.db

# path to sample file
samples: config/GSE139118_Pool1revcompbarcodes.txt

# path to hairpin file
hairpins: config/GSE139118_Pool1revcompshRNA.tsv

# path to fastq file
fastq: [config/DMSO.D2.R1_subset.fastq,
        config/DMSO.D2.R2_subset.fastq,
        config/DMSO.D4.R1_subset.fastq,
        config/DMSO.D4.R2_subset.fastq,
        config/DMSO.D8.R1_subset.fastq,
        config/DMSO.D8.R2_subset.fastq,
        config/DMSO.D10.R1_subset.fastq,
        config/DMSO.D10.R2_subset.fastq,
        config/IBET.D2.R1_subset.fastq,
        config/IBET.D2.R2_subset.fastq,
        config/IBET.D4.R1_subset.fastq,
        config/IBET.D4.R2_subset.fastq,
        config/IBET.D8.R1_subset.fastq,
        config/IBET.D8.R2_subset.fastq,
        config/IBET.D10.R1_subset.fastq,
        config/IBET.D10.R2_subset.fastq]


#one or more fastq filenames for reverse read 
readfile2: NULL

# hairpin sequence before barcode (TRUE or FALSE)
hairpinBeforeBarcode: TRUE

# specify contrasts
contrast:
  DMSO.D2_vs_DMSO.D8:
  - DMSO.D2-DMSO.D8
  DMSO.D2_vs_DMSO.D14:
  - DMSO.D2-DMSO.D10

# specify FDR threshold
FDR: 0.05

# specifiy fold change threshold
FC: 2.5