# specify organism
organism: org.Mm.eg.db

# path to sample file
samples: config/GSE139118_Pool1revcompbarcodes.txt

# path to hairpin file
hairpins: config/GSE139118_Pool1revcompshRNA.tsv

# path to fastq file
fastq: [config/IBET.D4.R1_subset.fastq,
        config/IBET.D4.R2_subset.fastq,
        config/IBET.D8.R1_subset.fastq,
        config/IBET.D8.R2_subset.fastq
        ]


#one or more fastq filenames for reverse read 
readfile2: NULL

# hairpin sequence before barcode (TRUE or FALSE)
hairpinBeforeBarcode: TRUE

# specify contrasts
contrast:
  IBET.D4_vs_IBET.D8:
  - IBET.D4-IBET.D8

# specify FDR threshold
FDR: 0.85

# specifiy fold change threshold
FC: 2.5