name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Formatting
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.22.0
      with:
        directory: .tests/integration
        snakefile: workflow/Snakefile
        args: "--lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: .tests/integration
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache --all-temp"
   -  name: Test report
      uses: snakemake/snakemake-github-action@v1.22.0
      with:
        directory: .tests/integration
        snakefile: workflow/Snakefile
        args: "--report report.zip"
