channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-annotationdbi
  - bioconductor-csaw
  - bioconductor-edger
  - bioconductor-limma
  - r-ggplot2
  - r-matrixstats
  - r-pheatmap
